name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - name: Lint
       run: yarn lint
  test:
  needs: [lint]
    runs-on: ubuntu-latest
    steps:
     - name: Test
       run: yarn test