name: Check
on: push
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier
        run: yarn prettier
  lint:
    needs: [prettier]
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: yarn test:sypress
